### ISSUE TITLE
feature request: http/3

### ISSUE THREAD

**Issue by hpvd** [bsiegel/http-version-indicator#13] opened 2018-11-13 11:52 UTC
show not only http/2 but also http/3 (Quic) if supported by ff and used for connection

**Comment by hpvd** [comment] 2018-11-13 11:56
https://en.wikipedia.org/wiki/QUIC
https://en.wikipedia.org/wiki/HTTP/3

**Comment by hpvd** [comment] 2018-11-13 12:03
About the Design of QUIC Firefox Transport Protocol:
http://www.edusoft.ro/brain/index.php/brain/article/download/686/764

**Comment by rubdos** [comment] 2019-09-27 07:14
Apparently, it's supported in FF since yesterday: https://www.zdnet.com/article/cloudflare-google-chrome-and-firefox-add-http3-support/ !

**Comment by aleksandrs-ledovskis** [comment] 2020-01-01 13:42
QUIC is usable (behind `network.http.http3.enabled` config flag) in latest Firefox Nightlies.

Have tested it with test page (https://quic.rocks:4433/) and it properly shows up as `HTTP/3`-backed in DevTools request list.

However, there currently seems no introspection avenues into request from [`webRequest`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest) API's to determine if load is happening over HTTP/3. For SPDY / HTTP/2 there is a helpful header (`X-Firefox-Spdy`) that is [being added by Firefox](https://dxr.mozilla.org/mozilla-central/rev/49ca7598efc001126341cd6dfacfe030c13e2f45/netwerk/protocol/http/Http2Stream.cpp#1084) if request was driven by HTTP/2, but there's no analogue for QUIC-world.

The `X-Firefox-Spdy` is [*the* header](https://github.com/bsiegel/http2-indicator/blob/3994ccca692ae6070ef25b816fed36e87a9853f3/background.js#L3) that makes http2-indicator extension tick. 

When website has HTTP/3 support it advertises such with addition of `Alt-Svc` header (e.g. `Alt-Svc | h3-24=":4433"; ma=3600`). But its presence can not be a guarantee that request did load via HTTP/3.

---

Hence, two options for HTTP/3 seem to exist:

1. Wait/ask for new introspection JS methods for `webRequest` API to cleanly get information about request's protocol in cross-browser way.
2. Wait/ask Mozilla to add new header (`X-Firefox-QUIC`) to response when loaded over HTTP/3.

**Comment by aparcar** [comment] 2020-05-13 03:50
Any update on this?

**Comment by Devvox93** [comment] 2020-06-28 14:37
Following this issue.
@bsiegel Are you still developing this (or just waiting for the HTTP/3 inspection options mentioned above?
The last update was 3 years ago...

**Comment by v2px** [comment] 2020-10-03 10:00
I don't think he gives a shit

**Comment by bsiegel** [comment] 2020-10-03 20:36
Removed inappropriate comment.

By way of an update, @aleksandrs-ledovskis provided an excellent overview of the current situation - Firefox does not currently expose any way of detecting whether a page is loaded over HTTP/3, and HTTP/3 support in Firefox is still not official - it's behind a flag you have to manually enable. In fact, the HTTP/3 specification isn't even final yet so the value used in the `Alt-Svc` header to advertise support for HTTP/3 (which as the commenter noted doesn't actually tell you if the request was actually loaded over HTTP/3) keeps changing based on the revision number of the spec as the spec evolves - it looks like it's currently at `h3-29`.

All this to say - I am definitely tracking this, but currently Firefox exposes no way for extensions to detect this. When that changes, I will definitely implement this feature request.

**Comment by v2px** [comment] 2020-10-03 21:01
Well, at least I triggered a response.
Also I found an extension that does it, so I'm out.
https://addons.mozilla.org/en-US/firefox/addon/http3-indicator/

**Comment by bsiegel** [comment] 2020-10-03 21:36
The above extension does precisely what I described above - it indicates whether the `Alt-Svc` header contains the string "h3", which does not actually tell you if the page was loaded over HTTP/3 or not. Feel free to use it if it suits your needs of course, but it's not providing you accurate information.

**Comment by Devvox93** [comment] 2020-10-04 14:56
@bsiegel Thank you for the update on this and for confirming you will implement support for this by the time Firefox makes this information available. Much appreciated :)

**Comment by hpvd** [comment] 2020-10-06 14:39
just a finding:
when activating support for http/3 via "about:config" search "http3" and set "false" to "true",
it's visible in Devtools/network: when you enable column "protocol"
![2020-10-06_16h34_17](https://user-images.githubusercontent.com/5681880/95216515-6f8e2a00-07f2-11eb-833a-c3aa4b828879.png)

**Comment by aleksandrs-ledovskis** [comment] 2020-10-06 16:25
@hpvd This functionality doesn't seem to have changed, as it was already pointed out in January's post.

For anyone interested, outside of Firefox Devtool's React wrapper juggling, the entry point of "Protocol" _version string one sees in request/response table seems to be https://dxr.mozilla.org/mozilla-central/rev/c68fe15a81fc2dc9fc5765f3be2573519c09b6c1/devtools/server/actors/network-monitor/network-observer.js#453. The code there handles response objects (`nsHttpResponse`) that are most likely not accessible to WebExtension add-ons.

**Comment by bsiegel** [comment] 2020-10-06 17:27
Just as a ray of hope, it looks like code was added to set a new header for HTTP/3 connections in July of this year: https://hg.mozilla.org/releases/mozilla-release/rev/ab74bac09a68daab7a7e94ad5ffd6b476a704777

I haven't actually seen this header get added to any responses yet, and I'm not sure what combination of things causes that code to be hit. But it gives us hope :) I can easily add this to the extension so that if it does start showing up, the extension will display it.

**Comment by aleksandrs-ledovskis** [comment] 2020-10-06 17:52
Nice find. The code is present only on mozilla-central though.

---

@ddragana, could you confirm that _what this extension is waiting for_ (i.e., a way to detect HTTP/3 requests from WebExtension scope) could provisionally be tied to `X-Firefox-Http3` header? And if confirmed, give some insight on timeline/what BZ bug to watch for/any idea when it might appear on Nightly/Beta builds?

**Comment by ddragana** [comment] 2020-11-04 21:31
How is HTTP2 detected? Using X-Firefox-Http2 header?

I will look into reasons why the X-Firefox-Http3 headers is not set.

**Comment by bsiegel** [comment] 2020-11-04 22:02
> How is HTTP2 detected? Using X-Firefox-Http2 header?
> 
> I will look into reasons why the X-Firefox-Http3 headers is not set.

Yes, that's exactly right. We're able to detect that Firefox did in fact use HTTP/2 for a given request if that header is present in the response. We would like to have some way of detecting that Firefox used HTTP/3 for a given request as well, and your change to add that header seems like a good approach.

**Comment by muety** [comment] 2021-03-02 21:35
Hi all, great discussion. Are there any news on this already?

**Comment by bsiegel** [comment] 2021-03-02 21:51
Unfortunately I don't believe there has been any progress on this. Firefox has not yet added a method for extensions to determine whether a page is loaded over HTTP/3 / QUIC. I have filed [bug 1696037](https://bugzilla.mozilla.org/show_bug.cgi?id=1696037) to request this capability. Since it should be a trivial change, hopefully the developers can implement it quickly but we'll just have to watch the bug and see.

**Comment by bsiegel** [comment] 2021-03-22 01:06
Good news! It looks like the above bug was fixed and merged and is set to ship in Firefox 88. I've added the supporting changes to this addon in f858539, and once I validate that the code works and I'm not seeing any regressions I will publish an updated version to AMO.

**Comment by hpvd** [comment] 2021-03-22 07:17
awesome! Looking forward...

**Comment by Nothing4You** [comment] 2021-03-23 12:50
looks good:
![image](https://user-images.githubusercontent.com/3694534/112148827-a1e3e600-8bde-11eb-8605-0060805d2078.png)

![image](https://user-images.githubusercontent.com/3694534/112148864-ab6d4e00-8bde-11eb-8055-9ccd1efb85da.png)

**Closed** 2021-04-27 07:38 UTC

**Comment by hpvd** [comment] 2021-04-27 07:53
Many thanks!

Just a comment on first impression of new version: https://github.com/bsiegel/http-version-indicator/issues/17

**Comment by Cai0407** [comment] 2021-04-27 09:20
Excellent!
v3.2 works fine with Firefox 78.10.0esr, 88.0, 89.0b4, and Nightly 90.0a1 on Windows 10.

on google.com (network.http.http3.enabled is default of each release)
- 78.10.0esr, 88.0 - HTTP/2
- 89.0b4 - HTTP/3 (h3-29)
- 90.0a1 (20210426213158) - HTTP/3 (h3-29)

Modification of Japanese locale file is good.
